-- ========================================================
-- BASE DE DATOS: direc_vitor (PostgreSQL / Supabase)
-- PLATAFORMA AGRÍCOLA DEL DISTRITO DE VALLE DE VÍTOR - AREQUIPA
-- === EJECUTAR AQUÍ EN SUPA BASE (o importar al crear la BD) ===
-- ========================================================

-- ─────────────── TIPOS ENUM ───────────────
DROP TYPE IF EXISTS reporte_estado_t CASCADE;
DROP TYPE IF EXISTS reporte_publicacion_tipo_t CASCADE;
DROP TYPE IF EXISTS reporte_tipo_objetivo_t CASCADE;
DROP TYPE IF EXISTS comentario_estado_t CASCADE;
DROP TYPE IF EXISTS comentario_publicacion_tipo_t CASCADE;
DROP TYPE IF EXISTS mensaje_tipo_t CASCADE;
DROP TYPE IF EXISTS publicidad_ubicacion_t CASCADE;
DROP TYPE IF EXISTS verificacion_tipo_t CASCADE;
DROP TYPE IF EXISTS transporte_estado_t CASCADE;
DROP TYPE IF EXISTS transporte_tipo_t CASCADE;
DROP TYPE IF EXISTS demanda_estado_t CASCADE;
DROP TYPE IF EXISTS demanda_urgencia_t CASCADE;
DROP TYPE IF EXISTS oferta_estado_t CASCADE;
DROP TYPE IF EXISTS usuario_tipo_t CASCADE;

CREATE TYPE usuario_tipo_t AS ENUM ('productor', 'comprador', 'transportista');
CREATE TYPE oferta_estado_t AS ENUM ('disponible', 'vendido', 'pausado');
CREATE TYPE demanda_urgencia_t AS ENUM ('Alta', 'Media', 'Baja');
CREATE TYPE demanda_estado_t AS ENUM ('activa', 'completada', 'cancelada');
CREATE TYPE transporte_tipo_t AS ENUM ('camioneta', 'camion', 'motocarga');
CREATE TYPE transporte_estado_t AS ENUM ('activo', 'inactivo');
CREATE TYPE verificacion_tipo_t AS ENUM ('registro', 'recuperacion', 'cambio_email');
CREATE TYPE publicidad_ubicacion_t AS ENUM ('inicio', 'lateral', 'footer', 'popup');
CREATE TYPE mensaje_tipo_t AS ENUM ('contacto', 'sistema', 'notificacion');
CREATE TYPE comentario_publicacion_tipo_t AS ENUM ('oferta', 'demanda', 'transporte');
CREATE TYPE comentario_estado_t AS ENUM ('activo', 'eliminado');
CREATE TYPE reporte_tipo_objetivo_t AS ENUM ('publicacion', 'comentario');
CREATE TYPE reporte_publicacion_tipo_t AS ENUM ('oferta', 'demanda', 'transporte');
CREATE TYPE reporte_estado_t AS ENUM ('pendiente', 'validado', 'descartado');

-- ─────────────── DROP DE TABLAS (orden correcto por FKs) ───────────────
DROP TABLE IF EXISTS reportes CASCADE;
DROP TABLE IF EXISTS comentarios CASCADE;
DROP TABLE IF EXISTS transportes CASCADE;
DROP TABLE IF EXISTS demandas CASCADE;
DROP TABLE IF EXISTS ofertas CASCADE;
DROP TABLE IF EXISTS mensajes CASCADE;
DROP TABLE IF EXISTS logs_sistema CASCADE;
DROP TABLE IF EXISTS verificaciones CASCADE;
DROP TABLE IF EXISTS configuracion CASCADE;
DROP TABLE IF EXISTS publicidad CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

-- ─────────────── TABLAS ───────────────
CREATE TABLE usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo usuario_tipo_t NOT NULL DEFAULT 'productor',
    dni_ruc VARCHAR(20) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL DEFAULT '',
    anexo VARCHAR(80) NOT NULL DEFAULT 'Sotillo',
    distrito VARCHAR(50) DEFAULT 'Valle de Vítor',
    ciudad VARCHAR(50) DEFAULT 'Arequipa',
    is_admin SMALLINT NOT NULL DEFAULT 0,
    verificado SMALLINT DEFAULT 1,
    activo SMALLINT DEFAULT 1,
    calificacion NUMERIC(2,1) DEFAULT 4.9,
    foto VARCHAR(255) DEFAULT 'default_user.jpg',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultimo_acceso TIMESTAMP DEFAULT NULL
);

CREATE TABLE categorias (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    icono VARCHAR(50) NOT NULL,
    activa SMALLINT DEFAULT 1
);

CREATE TABLE ofertas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    categoria_id INT NOT NULL,
    producto VARCHAR(100) NOT NULL,
    variedad VARCHAR(50) DEFAULT NULL,
    cantidad_ton NUMERIC(10,2) NOT NULL,
    precio_kg NUMERIC(8,2) NOT NULL,
    anexo VARCHAR(80) NOT NULL DEFAULT 'Sotillo',
    ubicacion_chacra VARCHAR(150) NOT NULL,
    fecha_cosecha DATE NOT NULL,
    es_organico SMALLINT DEFAULT 0,
    descripcion TEXT,
    imagen VARCHAR(255) DEFAULT 'images/harvest_default.jpg',
    estado oferta_estado_t DEFAULT 'disponible',
    vistas INT DEFAULT 0,
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE CASCADE
);

CREATE TABLE demandas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    tipo_comprador VARCHAR(80) NOT NULL,
    producto VARCHAR(100) NOT NULL,
    cantidad_ton NUMERIC(10,2) NOT NULL,
    precio_max_kg NUMERIC(8,2) NOT NULL,
    destino VARCHAR(100) NOT NULL,
    fecha_cosecha DATE DEFAULT NULL,
    urgencia demanda_urgencia_t DEFAULT 'Media',
    descripcion TEXT,
    estado demanda_estado_t DEFAULT 'activa',
    vistas INT DEFAULT 0,
    fecha_publicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE transportes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    tipo transporte_tipo_t NOT NULL DEFAULT 'camioneta',
    telefono VARCHAR(20) NOT NULL,
    placa VARCHAR(20) DEFAULT NULL,
    anexo VARCHAR(80) NOT NULL,
    cobertura VARCHAR(150) DEFAULT NULL,
    descripcion TEXT,
    estado transporte_estado_t DEFAULT 'activo',
    vistas INT DEFAULT 0,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE verificaciones (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT DEFAULT NULL,
    email VARCHAR(100) NOT NULL,
    codigo VARCHAR(10) NOT NULL,
    tipo verificacion_tipo_t DEFAULT 'registro',
    usado SMALLINT DEFAULT 0,
    expira_en TIMESTAMP NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE publicidad (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    descripcion TEXT,
    imagen VARCHAR(255) NOT NULL,
    enlace VARCHAR(255) DEFAULT NULL,
    ubicacion publicidad_ubicacion_t DEFAULT 'inicio',
    activa SMALLINT DEFAULT 1,
    orden INT DEFAULT 0,
    fecha_inicio DATE DEFAULT NULL,
    fecha_fin DATE DEFAULT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mensajes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emisor_id INT NOT NULL,
    receptor_id INT DEFAULT NULL,
    asunto VARCHAR(150) NOT NULL,
    mensaje TEXT NOT NULL,
    leido SMALLINT DEFAULT 0,
    tipo mensaje_tipo_t DEFAULT 'contacto',
    referencia_tipo VARCHAR(50) DEFAULT NULL,
    referencia_id INT DEFAULT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (emisor_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (receptor_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE logs_sistema (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT DEFAULT NULL,
    accion VARCHAR(100) NOT NULL,
    tabla_afectada VARCHAR(50) DEFAULT NULL,
    registro_id INT DEFAULT NULL,
    detalles TEXT DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    user_agent VARCHAR(255) DEFAULT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE configuracion (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(100) NOT NULL UNIQUE,
    valor TEXT NOT NULL,
    descripcion VARCHAR(255) DEFAULT NULL,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comentarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_tipo comentario_publicacion_tipo_t NOT NULL,
    publicacion_id INT NOT NULL,
    usuario_id INT NOT NULL,
    comentario TEXT NOT NULL,
    estado comentario_estado_t DEFAULT 'activo',
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE reportes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_objetivo reporte_tipo_objetivo_t NOT NULL,
    publicacion_tipo reporte_publicacion_tipo_t DEFAULT NULL,
    publicacion_id INT DEFAULT NULL,
    comentario_id INT DEFAULT NULL,
    usuario_reportante_id INT NOT NULL,
    motivo VARCHAR(100) NOT NULL,
    detalles TEXT DEFAULT NULL,
    estado reporte_estado_t DEFAULT 'pendiente',
    resolucion_nota TEXT DEFAULT NULL,
    admin_id INT DEFAULT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resuelto_en TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (usuario_reportante_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (comentario_id) REFERENCES comentarios(id) ON DELETE CASCADE,
    FOREIGN KEY (admin_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- ─────────────── TRIGGERS (equivalente a ON UPDATE CURRENT_TIMESTAMP) ───────────────
CREATE OR REPLACE FUNCTION set_fecha_actualizacion() RETURNS trigger AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_actualizado_en() RETURNS trigger AS $$
BEGIN
    NEW.actualizado_en = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ofertas_upd BEFORE UPDATE ON ofertas FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_demandas_upd BEFORE UPDATE ON demandas FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_transportes_upd BEFORE UPDATE ON transportes FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_publicidad_upd BEFORE UPDATE ON publicidad FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();
CREATE TRIGGER trg_configuracion_upd BEFORE UPDATE ON configuracion FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();
CREATE TRIGGER trg_comentarios_upd BEFORE UPDATE ON comentarios FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

-- ─────────────── ÍNDICES ───────────────
CREATE INDEX idx_ofertas_usuario ON ofertas(usuario_id);
CREATE INDEX idx_ofertas_estado ON ofertas(estado);
CREATE INDEX idx_ofertas_anexo ON ofertas(anexo);
CREATE INDEX idx_demandas_usuario ON demandas(usuario_id);
CREATE INDEX idx_demandas_estado ON demandas(estado);
CREATE INDEX idx_transportes_usuario ON transportes(usuario_id);
CREATE INDEX idx_transportes_estado ON transportes(estado);
CREATE INDEX idx_verificaciones_email ON verificaciones(email);
CREATE INDEX idx_mensajes_emisor ON mensajes(emisor_id);
CREATE INDEX idx_mensajes_receptor ON mensajes(receptor_id);
CREATE INDEX idx_logs_usuario ON logs_sistema(usuario_id);
CREATE INDEX idx_logs_creado ON logs_sistema(creado_en);
CREATE INDEX idx_comentarios_pub ON comentarios(publicacion_tipo, publicacion_id);
CREATE INDEX idx_comentarios_usuario ON comentarios(usuario_id);
CREATE INDEX idx_reportes_estado ON reportes(estado);
CREATE INDEX idx_reportes_tipo ON reportes(tipo_objetivo);

-- ─────────────── DATOS DE PRUEBA (seed) ───────────────
INSERT INTO categorias (id, nombre, icono) VALUES
(1, 'Hortalizas y Verduras', 'fa-seedling'),
(2, 'Frutas y Viñedos', 'fa-wine-bottle'),
(3, 'Cereales y Forrajes', 'fa-wheat-awn'),
(4, 'Tubérculos y Raíces', 'fa-carrot'),
(5, 'Especies y Pimientos', 'fa-pepper-hot');

INSERT INTO usuarios (id, nombre, tipo, dni_ruc, telefono, email, password, anexo, distrito, ciudad, is_admin, verificado, calificacion) VALUES
(1, 'Fundo Don Mateo - Anexo Sotillo',       'productor',    '10458291034', '+51 984 512 301', 'donmateo@campodirecto.pe',   '$2a$10$pBj/NvrV1zVqpALbFd2QceQx0wAD2UryqWjazch0WfNweDn7gtFsK', 'Sotillo',       'Valle de Vítor', 'Arequipa', 0, 1, 4.9),
(2, 'Agrícola Vítor - José Quispe',          'productor',    '20601234567', '+51 947 182 940', 'jquispe@campodirecto.pe',     '$2a$10$pBj/NvrV1zVqpALbFd2QceQx0wAD2UryqWjazch0WfNweDn7gtFsK', 'Pueblo Viejo',  'Valle de Vítor', 'Arequipa', 0, 1, 4.8),
(3, 'Asociación de Regantes San Luis',       'productor',    '20491029384', '+51 951 823 104', 'coop_vitor@campodirecto.pe',  '$2a$10$pBj/NvrV1zVqpALbFd2QceQx0wAD2UryqWjazch0WfNweDn7gtFsK', 'San Luis',      'Valle de Vítor', 'Arequipa', 0, 1, 5.0),
(4, 'Mercado Mayorista Río Seco Arequipa',   'comprador',    '20509182736', '+51 998 123 456', 'compras@rioseco.pe',          '$2a$10$pBj/NvrV1zVqpALbFd2QceQx0wAD2UryqWjazch0WfNweDn7gtFsK', 'Sotillo',       'Arequipa',       'Arequipa', 0, 1, 4.9),
(5, 'Exportadora Arequipa Agro',             'comprador',    '20102938475', '+51 977 456 123', 'compras@aqpagro.pe',          '$2a$10$pBj/NvrV1zVqpALbFd2QceQx0wAD2UryqWjazch0WfNweDn7gtFsK', 'Sotillo',       'Arequipa',       'Arequipa', 0, 1, 4.7),
(6, 'Transportes Don Mateo',                 'transportista','10458291034', '+51 984 512 301', 'transportes@donmateo.pe',     '$2a$10$pBj/NvrV1zVqpALbFd2QceQx0wAD2UryqWjazch0WfNweDn7gtFsK', 'Sotillo',       'Valle de Vítor', 'Arequipa', 0, 1, 4.9),
(7, 'MotoFletes José Quispe',                'transportista','20601234567', '+51 947 182 940', 'fletes@quispe.pe',            '$2a$10$pBj/NvrV1zVqpALbFd2QceQx0wAD2UryqWjazch0WfNweDn7gtFsK', 'Pueblo Viejo',  'Valle de Vítor', 'Arequipa', 0, 1, 4.8),
(8, 'Camionetas San Luis',                   'transportista','20491029384', '+51 951 823 104', 'camionetas@santluis.pe',      '$2a$10$pBj/NvrV1zVqpALbFd2QceQx0wAD2UryqWjazch0WfNweDn7gtFsK', 'San Luis',      'Valle de Vítor', 'Arequipa', 0, 1, 5.0),
(99, 'Administrador Direct Vitor',            'productor',    '00000000',    '+51 999 000 000', 'admin',                      '$2a$10$35C4mp3me/YDUy9qVN7YhutbGPgBiqa/H1CVOBKL6dtk8UinewYh.', 'Sotillo',       'Valle de Vítor', 'Arequipa', 1, 1, 5.0);

INSERT INTO ofertas (id, usuario_id, categoria_id, producto, variedad, cantidad_ton, precio_kg, anexo, ubicacion_chacra, fecha_cosecha, es_organico, descripcion, imagen) VALUES
(1, 1, 1, 'Cebolla Roja Arequipeña', 'Roja Camaneja Grano Grande', 20.00, 1.80, 'Sotillo', 'Anexo Sotillo, Sector 2', '2026-08-05', 0, 'Cebolla roja de excelente firmeza y color, cosechada directo en el Anexo Sotillo de Vítor. Lista para despacho a mercados.', 'images/automaticas/harvest_cebolla.jpg'),
(2, 2, 2, 'Uva Italia pisco y mesa', 'Italia Aromática', 15.00, 3.50, 'Pueblo Viejo', 'Anexo Pueblo Viejo, Parcela 8', '2026-08-12', 1, 'Uva Italia aromática de alta graduación brix. Ideal para elaboración de pisco artesanal o consumo de mesa.', 'images/automaticas/harvest_uva.jpg'),
(3, 3, 5, 'Ají Paprika de Exportación', 'Paprika Mesa', 12.00, 5.20, 'San Luis', 'Anexo San Luis, Parcela 15', '2026-08-08', 1, 'Ají Paprika de gran intensidad de color ASTA. Secado natural en chacra del Anexo San Luis.', 'images/automaticas/harvest_aji_panca.jpg'),
(4, 1, 1, 'Tomate Katia', 'Katia Primera', 18.00, 2.10, 'La Caleta', 'Anexo La Caleta, Sector Bajo', '2026-08-02', 0, 'Tomate Katia parejo y bien madurado, ideal para restaurantes y mercados de Arequipa.', 'images/automaticas/harvest_tomate.jpg');

INSERT INTO demandas (id, usuario_id, tipo_comprador, producto, cantidad_ton, precio_max_kg, destino, fecha_cosecha, urgencia, descripcion) VALUES
(1, 4, 'Mercado Mayorista', 'Cebolla Roja Arequipeña', 15.00, 2.00, 'Arequipa - Río Seco', '2026-08-20', 'Alta', 'Requerimos cebolla roja proveniente del Valle de Vítor clasificada por tamaño.'),
(2, 5, 'Exportadora Agrícola', 'Uva Quebranta / Italia', 30.00, 3.80, 'Arequipa - Planta de Procesamiento', '2026-08-25', 'Media', 'Compramos cosecha completa de viñedos de Vítor para pisco y exportación.');

INSERT INTO transportes (id, usuario_id, nombre, tipo, telefono, placa, anexo, cobertura, descripcion) VALUES
(1, 6, 'Transportes Don Mateo', 'camion', '+51 984 512 301', 'A5B-123', 'Sotillo', 'Vítor, Arequipa centro, mayoristas', 'Camión frigorífico para traslado de cosechas, carga completa por tonelada.'),
(2, 7, 'MotoFletes José Quispe', 'motocarga', '+51 947 182 940', 'M8-4567', 'Pueblo Viejo', 'Anexos de Valle de Vítor', 'Motocarga ágil para traslados cortos entre anexos y chacras.'),
(3, 8, 'Camionetas San Luis', 'camioneta', '+51 951 823 104', 'C1D-789', 'San Luis', 'Arequipa y alrededores', 'Camioneta pick up para carga liviana y media, servicios a domicilio.');

INSERT INTO comentarios (id, publicacion_tipo, publicacion_id, usuario_id, comentario, estado) VALUES
(1, 'oferta', 1, 4, '¿Tienen disponibilidad de envío directo al Mercado Río Seco este fin de semana?', 'activo'),
(2, 'oferta', 1, 1, 'Sí estimado, contamos con camión propio para despacho a Río Seco los sábados.', 'activo'),
(3, 'oferta', 2, 5, 'Excelente calidad de uva Italia en Pueblo Viejo. Nos contactaremos al WhatsApp.', 'activo'),
(4, 'demanda', 1, 1, 'Tengo disponible 15 toneladas en Sotillo listas para cargar.', 'activo');

INSERT INTO reportes (id, tipo_objetivo, publicacion_tipo, publicacion_id, comentario_id, usuario_reportante_id, motivo, detalles, estado) VALUES
(1, 'publicacion', 'oferta', 3, NULL, 4, 'Verificación de precio', 'Consultar si el precio incluye selección o es al barrer en chacra.', 'pendiente');

INSERT INTO publicidad (titulo, descripcion, imagen, enlace, ubicacion, activa, orden) VALUES
('Bienvenido a Direct Vitor', 'Plataforma agrícola del Valle de Vítor, Arequipa', 'images/publicidad/pub_1788756445_15701518.jpg', NULL, 'inicio', 1, 1);

INSERT INTO configuracion (clave, valor, descripcion) VALUES
('nombre_sistema', 'Direct Vitor', 'Nombre de la plataforma'),
('version', '1.0.0', 'Versión actual del sistema'),
('mantenimiento', '0', 'Modo mantenimiento (0=off, 1=on)'),
('registro_activo', '1', 'Permitir registros nuevos (0=off, 1=on)'),
('publicidad_activa', '1', 'Mostrar publicidad (0=off, 1=on)');

-- ─────────────── SINCRONIZAR SECUENCIAS (por los IDs explícitos del seed) ───────────────
SELECT setval('usuarios_id_seq', (SELECT COALESCE(MAX(id), 1) FROM usuarios));
SELECT setval('categorias_id_seq', (SELECT COALESCE(MAX(id), 1) FROM categorias));
SELECT setval('ofertas_id_seq', (SELECT COALESCE(MAX(id), 1) FROM ofertas));
SELECT setval('demandas_id_seq', (SELECT COALESCE(MAX(id), 1) FROM demandas));
SELECT setval('transportes_id_seq', (SELECT COALESCE(MAX(id), 1) FROM transportes));
SELECT setval('comentarios_id_seq', (SELECT COALESCE(MAX(id), 1) FROM comentarios));
SELECT setval('reportes_id_seq', (SELECT COALESCE(MAX(id), 1) FROM reportes));
SELECT setval('publicidad_id_seq', (SELECT COALESCE(MAX(id), 1) FROM publicidad));
SELECT setval('configuracion_id_seq', (SELECT COALESCE(MAX(id), 1) FROM configuracion));